### ISSUE TITLE
LambdaLayer dictionary rename.

### ISSUE THREAD

**Issue by zsdonghao** [ritchieng/wideresnet-tensorlayer#1]
Hi Ritchie, can you change the `kwargs` to `fn_args` in the LambdaLayer?

I am using `fn_args` in the release version now.

**Comment by ritchieng** [comment]
Done in accordance with your commit: https://github.com/zsdonghao/tensorlayer/commit/73365439dbb3e7ba7f106c187f5b9b2d92bbadb7

Commit of change:
https://github.com/ritchieng/wideresnet-tensorlayer/commit/627e5b6f6d417f89860f4565f80073379678f787
